### ISSUE TITLE
组件怎么重复渲染，类似vue的v-for怎么实现？

### ISSUE THREAD

**Issue by qiuquanwu** [Ale-js/ale#1]
建议做一个这样的功能。组件增加一个repeat属性，指定循环的变量名，在渲染时自动重复生产组件。

**Comment by qiuquanwu** [comment]
![avatar](http://thyrsi.com/t6/658/1547659698x2890202791.png)

**Comment by billdong9** [comment]
类似v-for这种功能我们会单独开一个插件来做，大概2月份发布吧
